using WinTube.Core;
using WinTube.Core.InnerTube;
using WinTube.Core.Player;

namespace WinTube.Core.Tests;

public class StreamServiceTests
{
    private const string VisitorPage = """{"visitorData":"VDATA"}""";

    private const string HlsResponse = """
        {"playabilityStatus":{"status":"OK"},
         "videoDetails":{"shortDescription":"Timestamps: 0:30 intro. See https://example.com for more."},
         "streamingData":{
           "hlsManifestUrl":"https://manifest.example/master.m3u8",
           "adaptiveFormats":[
             {"itag":140,"audioTrack":{"id":"de-DE.3","audioIsDefault":true}},
             {"itag":141,"audioTrack":{"id":"en-US.4","audioIsDefault":false}}]}}
        """;

    private const string Itag18Response = """
        {"playabilityStatus":{"status":"OK"},
         "streamingData":{"formats":[
           {"itag":22,"mimeType":"video/mp4","signatureCipher":"blocked"},
           {"itag":18,"mimeType":"video/mp4; codecs=\"avc1\"","url":"https://v.example/18.mp4"}]}}
        """;

    private const string LoginRequired = """
        {"playabilityStatus":{"status":"LOGIN_REQUIRED","reason":"Sign in to confirm your age"}}
        """;

    private const string CaptionsResponse = """
        {"playabilityStatus":{"status":"OK"},
         "streamingData":{"hlsManifestUrl":"https://x/m.m3u8"},
         "videoDetails":{"shortDescription":"d"},
         "captions":{"playerCaptionsTracklistRenderer":{"captionTracks":[
           {"baseUrl":"https://www.youtube.com/api/timedtext?v=a&lang=en","languageCode":"en",
            "name":{"runs":[{"text":"English"}]}},
           {"baseUrl":"https://www.youtube.com/api/timedtext?v=a&lang=da&caps=asr","languageCode":"da",
            "kind":"asr","name":{"simpleText":"Danish (auto-generated)"}}]}}}
        """;

    private const string NoCaptionsResponse = """
        {"playabilityStatus":{"status":"OK"},
         "streamingData":{"hlsManifestUrl":"https://x/m.m3u8"},"videoDetails":{}}
        """;

    private const string Itag18CaptionsResponse = """
        {"playabilityStatus":{"status":"OK"},
         "streamingData":{"formats":[
           {"itag":18,"mimeType":"video/mp4","url":"https://v.example/18.mp4"}]},
         "captions":{"playerCaptionsTracklistRenderer":{"captionTracks":[
           {"baseUrl":"https://www.youtube.com/api/timedtext?v=a&lang=en","languageCode":"en"},
           {"languageCode":"fr","name":{"simpleText":"French"}},
           {"baseUrl":"https://www.youtube.com/api/timedtext?v=a&lang=de","name":{"simpleText":"German"}}]}}}
        """;

    /// Routes the visitor-data page scrape and per-client /player calls to canned responses.
    private static StreamService Make(Func<string, string> playerResponseForHost,
        out List<string> playerHosts)
    {
        var hosts = new List<string>();
        var handler = new StubHttpHandler((request, _) =>
        {
            var url = request.RequestUri!.ToString();
            if (url.Contains("/tv?bpctr")) return StubHttpHandler.JsonResponse(VisitorPage);
            hosts.Add(request.RequestUri!.Host);
            return StubHttpHandler.JsonResponse(playerResponseForHost(request.RequestUri!.Host));
        });
        var http = new HttpClient(handler);
        playerHosts = hosts;
        return new StreamService(
            new InnerTubeClient(http, new Secrets("K", "", "")), new VisitorDataStore(http));
    }

    [Fact]
    public async Task Resolve_PrefersHlsFromVisionOs()
    {
        var service = Make(_ => HlsResponse, out _);
        var stream = await service.ResolveAsync("abc");
        Assert.Equal("https://manifest.example/master.m3u8", stream.Url.ToString());
        Assert.True(stream.IsAdaptive);
        Assert.Equal(ClientKind.VisionOs, stream.Client);
        Assert.Equal("de-DE", stream.OriginalAudioLanguage);
        Assert.Equal("Timestamps: 0:30 intro. See https://example.com for more.", stream.Description);
    }

    [Fact]
    public async Task Resolve_ParsesCaptionTracks_BothNameShapes_AndAsrFlag()
    {
        var stream = await Make(_ => CaptionsResponse, out _).ResolveAsync("abc");
        Assert.Equal(2, stream.Captions.Count);
        Assert.Equal(("en", "English", false),
            (stream.Captions[0].Language, stream.Captions[0].Name, stream.Captions[0].IsAutoGenerated));
        Assert.True(stream.Captions[1].IsAutoGenerated);
        Assert.Equal("Danish (auto-generated)", stream.Captions[1].Name);
        Assert.Contains("fmt=vtt", stream.Captions[0].VttUrl);
        Assert.EndsWith("&tlang=en", stream.Captions[1].TranslatedVttUrl("en"));
    }

    [Fact]
    public async Task Resolve_NoCaptionsKey_YieldsEmptyList()
    {
        var stream = await Make(_ => NoCaptionsResponse, out _).ResolveAsync("abc");
        Assert.Empty(stream.Captions);
    }

    [Fact]
    public async Task Resolve_MuxedBranch_ParsesCaptions_SkipsMalformed_NameFallsBackToLanguage()
    {
        var service = Make(
            host => host == "youtubei.googleapis.com" ? Itag18CaptionsResponse : LoginRequired, out _);
        var stream = await service.ResolveAsync("abc");
        Assert.False(stream.IsAdaptive);
        var track = Assert.Single(stream.Captions);  // no baseUrl / no languageCode entries dropped
        Assert.Equal(("en", "en", false), (track.Language, track.Name, track.IsAutoGenerated));
    }

    private const string HostileCaptionsResponse = """
        {"playabilityStatus":{"status":"OK"},
         "streamingData":{"hlsManifestUrl":"https://x/m.m3u8"},
         "captions":{"playerCaptionsTracklistRenderer":{"captionTracks":[
           {"baseUrl":"\\\\evil\\share\\x.vtt","languageCode":"xx"},
           {"baseUrl":"file:///C:/Windows/win.ini","languageCode":"yy"},
           {"baseUrl":"http://www.youtube.com/api/timedtext?v=a&lang=zz","languageCode":"zz"},
           {"baseUrl":"https://www.youtube.com/api/timedtext?v=a;lang=ww","languageCode":"ww"},
           {"baseUrl":"/api/timedtext?v=a","languageCode":"vv"},
           {"baseUrl":"https://www.youtube.com/api/timedtext?v=a&lang=en","languageCode":"en"}]}}}
        """;

    [Fact]
    public async Task Resolve_SkipsCaptionTracks_WithNonHttpsAbsoluteOrSemicolonUrls()
    {
        var stream = await Make(_ => HostileCaptionsResponse, out _).ResolveAsync("abc");
        var track = Assert.Single(stream.Captions);
        Assert.Equal("en", track.Language);
    }

    [Fact]
    public void CaptionTrack_VttUrl_AppendsWithCorrectSeparator()
    {
        Assert.Equal("https://t/x?v=a&fmt=vtt", new CaptionTrack("https://t/x?v=a", "en", "English", false).VttUrl);
        Assert.Equal("https://t/x?fmt=vtt", new CaptionTrack("https://t/x", "en", "English", false).VttUrl);
    }

    [Fact]
    public async Task Resolve_NoShortDescription_LeavesDescriptionNull()
    {
        var service = Make(
            host => host == "youtubei.googleapis.com" ? Itag18Response : LoginRequired, out _);
        var stream = await service.ResolveAsync("abc");
        Assert.Null(stream.Description);
    }

    [Fact]
    public async Task Resolve_FallsBackToAndroidItag18OnLoginRequired()
    {
        // VISIONOS (www.youtube.com) is gated; ANDROID (youtubei.googleapis.com) serves itag 18.
        var service = Make(
            host => host == "youtubei.googleapis.com" ? Itag18Response : LoginRequired, out _);
        var stream = await service.ResolveAsync("abc");
        Assert.Equal("https://v.example/18.mp4", stream.Url.ToString());
        Assert.False(stream.IsAdaptive);
        Assert.Equal(ClientKind.Android, stream.Client);
        Assert.Null(stream.OriginalAudioLanguage);
    }

    [Fact]
    public async Task Resolve_AllClientsGated_SurfacesYouTubesReason()
    {
        var service = Make(_ => LoginRequired, out _);
        var ex = await Assert.ThrowsAsync<StreamException>(() => service.ResolveAsync("abc"));
        Assert.Contains("Sign in to confirm your age", ex.Message);
    }

    [Fact]
    public async Task Resolve_After_SkipsPastFailedClient()
    {
        var service = Make(
            host => host == "youtubei.googleapis.com" ? Itag18Response : HlsResponse,
            out var playerHosts);
        var stream = await service.ResolveAsync("abc", after: ClientKind.VisionOs);
        Assert.Equal(ClientKind.Android, stream.Client);
        Assert.DoesNotContain("www.youtube.com", playerHosts);  // VISIONOS never called
    }
}
