using WinTube.Core.Player;

namespace WinTube.Core.Tests;

public class SubtitleSelectionTests
{
    [Fact]
    public void Choose_PrefersManualOverAsr_AndMatchesRegionalVariants()
    {
        var tracks = new List<CaptionTrack>
        {
            new("https://t?lang=en&caps=asr", "en", "English (auto)", true),
            new("https://t?lang=en-US", "en-US", "English (US)", false),
        };
        var choice = SubtitleSelection.Choose(tracks, "en");
        Assert.False(choice!.IsTranslation);
        Assert.Equal("en-US", choice.Language);
    }

    [Fact]
    public void Choose_FallsBackToTranslation_OnlyForEnglishPreference()
    {
        var tracks = new List<CaptionTrack> { new("https://t?lang=ja", "ja", "Japanese", false) };
        var en = SubtitleSelection.Choose(tracks, "en");
        Assert.True(en!.IsTranslation);
        Assert.EndsWith("&tlang=en", en.Url);
        Assert.Null(SubtitleSelection.Choose(tracks, "da"));   // no Danish track, no auto-translate
    }

    [Fact]
    public void Choose_NullPreference_ReturnsNull()
    {
        var tracks = new List<CaptionTrack> { new("https://t?lang=en", "en", "English", false) };
        Assert.Null(SubtitleSelection.Choose(tracks, null));
    }

    [Fact]
    public void Choose_EmptyTracks_ReturnsNull()
    {
        var tracks = new List<CaptionTrack>();
        Assert.Null(SubtitleSelection.Choose(tracks, "en"));
    }

    [Fact]
    public void Choose_PrefsersExactLanguageMatch()
    {
        var tracks = new List<CaptionTrack>
        {
            new("https://t?lang=en-GB", "en-GB", "English (UK)", false),
            new("https://t?lang=en-US", "en-US", "English (US)", false),
        };
        var choice = SubtitleSelection.Choose(tracks, "en-GB");
        Assert.Equal("en-GB", choice!.Language);
    }

    [Fact]
    public void Choose_PrefixMatchForRegionalVariant()
    {
        var tracks = new List<CaptionTrack>
        {
            new("https://t?lang=en-US", "en-US", "English (US)", false),
        };
        var choice = SubtitleSelection.Choose(tracks, "en");
        Assert.Equal("en-US", choice!.Language);
    }

    [Fact]
    public void Choose_PrefersManualOverAutoGenerated()
    {
        var tracks = new List<CaptionTrack>
        {
            new("https://t?lang=en", "en", "English (auto)", true),
            new("https://t?lang=en", "en", "English", false),
        };
        var choice = SubtitleSelection.Choose(tracks, "en");
        Assert.Equal("English", choice!.Label);
    }

    [Fact]
    public void Choose_FallsBackToAsrWhenNoManualTrack()
    {
        var tracks = new List<CaptionTrack>
        {
            new("https://t?lang=en", "en", "English (auto)", true),
        };
        var choice = SubtitleSelection.Choose(tracks, "en");
        Assert.Equal("English (auto)", choice!.Label);
    }

    [Fact]
    public void Choose_TranslationUsesFirstNonAutoTrackOrFirstTrack()
    {
        var tracks = new List<CaptionTrack>
        {
            new("https://t?lang=ja-asr", "ja", "Japanese (auto)", true),
            new("https://t?lang=ja", "ja", "Japanese", false),
        };
        var choice = SubtitleSelection.Choose(tracks, "en");
        Assert.True(choice!.IsTranslation);
        Assert.Contains("ja", choice.Url);
        Assert.EndsWith("&tlang=en", choice.Url);
    }

    [Fact]
    public void Choose_TranslationLabelIsTranslateToEnglish()
    {
        var tracks = new List<CaptionTrack> { new("https://t?lang=ja", "ja", "Japanese", false) };
        var choice = SubtitleSelection.Choose(tracks, "en");
        Assert.Equal("Translate to English", choice!.Label);
    }

    [Fact]
    public void OnMuteChanged_OffWithMute_ReturnsAutoMute()
    {
        Assert.Equal(SubtitleMode.AutoMute, SubtitleMuteMachine.OnMuteChanged(SubtitleMode.Off, true));
    }

    [Fact]
    public void OnMuteChanged_AutoMuteWithUnmute_ReturnsOff()
    {
        Assert.Equal(SubtitleMode.Off, SubtitleMuteMachine.OnMuteChanged(SubtitleMode.AutoMute, false));
    }

    [Fact]
    public void OnMuteChanged_ManualWithUnmute_StaysManual()
    {
        Assert.Equal(SubtitleMode.Manual, SubtitleMuteMachine.OnMuteChanged(SubtitleMode.Manual, false));
    }

    [Fact]
    public void OnMuteChanged_ManualWithMute_StaysManual()
    {
        Assert.Equal(SubtitleMode.Manual, SubtitleMuteMachine.OnMuteChanged(SubtitleMode.Manual, true));
    }

    [Fact]
    public void OnMuteChanged_OffWithoutMute_StaysOff()
    {
        Assert.Equal(SubtitleMode.Off, SubtitleMuteMachine.OnMuteChanged(SubtitleMode.Off, false));
    }

    [Fact]
    public void OnMuteChanged_AutoMuteWithMute_StaysAutoMute()
    {
        Assert.Equal(SubtitleMode.AutoMute, SubtitleMuteMachine.OnMuteChanged(SubtitleMode.AutoMute, true));
    }

    [Fact]
    public void OnManualPick_PickedTrack_ReturnsManual()
    {
        Assert.Equal(SubtitleMode.Manual, SubtitleMuteMachine.OnManualPick(false));
    }

    [Fact]
    public void OnManualPick_PickedOff_ReturnsOff()
    {
        Assert.Equal(SubtitleMode.Off, SubtitleMuteMachine.OnManualPick(true));
    }
}
