namespace WinTube.Core.Player;

/// One subtitle track from the player response's captionTracks. Url is a pre-signed timedtext
/// URL, valid ~7 h and bound to the requesting IP — consume it at playback time, never persist it.
/// IsAutoGenerated is YouTube's ASR (kind "asr"); Name is the track's own display name.
public sealed record CaptionTrack(string Url, string Language, string Name, bool IsAutoGenerated)
{
    public string VttUrl => Url + (Url.Contains('?') ? "&" : "?") + "fmt=vtt";

    /// Machine translation into `lang`, served by the same endpoint as the source track.
    public string TranslatedVttUrl(string lang) => VttUrl + "&tlang=" + lang;
}
