namespace WinTube.Core.Player;

/// What the player should attach for a video, given the tracks and the persisted preference.
public static class SubtitleSelection
{
    /// Preference chain: best language match → translation of the default track → null.
    /// Match tiers, best first: exact code (en-GB = en-GB); regional variant of the preference
    /// (preference "en", code "en-US"); same primary subtag (preference "en-GB", code "en" or
    /// "en-US"; "pt-BR" vs "pt"). Order: manual before ASR (any matching tier), then tier within
    /// that, then track order — so a human-made regional track still beats an exact ASR one
    /// (the pre-existing behaviour), and a persisted regional pick still finds the
    /// bare-language track on a later video.
    /// The translation rung fires when the preference's primary subtag is "en" and no track matched.
    public static SubtitleChoice? Choose(IReadOnlyList<CaptionTrack> tracks, string? preferredLanguage)
    {
        if (preferredLanguage == null || tracks.Count == 0)
            return null;

        var best = tracks
            .Select((t, i) => (Track: t, Index: i, Tier: MatchTier(t.Language, preferredLanguage)))
            .Where(x => x.Tier > 0)
            .OrderBy(x => x.Track.IsAutoGenerated)
            .ThenBy(x => x.Tier)
            .ThenBy(x => x.Index)
            .Select(x => x.Track)
            .FirstOrDefault();

        if (best != null)
            return new SubtitleChoice(best.VttUrl, best.Language, best.Name, false);

        if (PrimarySubtag(preferredLanguage) == "en")
        {
            var sourceTrack = tracks.FirstOrDefault(t => !t.IsAutoGenerated) ?? tracks[0];
            return new SubtitleChoice(
                sourceTrack.TranslatedVttUrl("en"),
                "en",
                "Translate to English",
                true);
        }

        return null;
    }

    /// 1 exact, 2 regional variant of the preference, 3 same primary subtag, 0 no match.
    private static int MatchTier(string trackLanguage, string preferredLanguage)
    {
        if (trackLanguage.Equals(preferredLanguage, StringComparison.Ordinal)) return 1;
        if (trackLanguage.StartsWith(preferredLanguage + "-", StringComparison.Ordinal)) return 2;
        return PrimarySubtag(trackLanguage).Equals(PrimarySubtag(preferredLanguage), StringComparison.Ordinal)
            ? 3 : 0;
    }

    private static string PrimarySubtag(string language)
    {
        var dash = language.IndexOf('-');
        return dash < 0 ? language : language[..dash];
    }
}

/// A subtitle choice to attach. IsTranslation true means Url is the source track's TranslatedVttUrl("en");
/// false means Url is a track's VttUrl.
public sealed record SubtitleChoice(string Url, string Language, string Label, bool IsTranslation);

public enum SubtitleMode { Off, Manual, AutoMute }

/// Pure transition table for the mute automation. The caller owns current mode + muted flag.
public static class SubtitleMuteMachine
{
    /// Returns the new mode when mute state flips. Off+mute→AutoMute (callers attach the best
    /// track); AutoMute+unmute→Off; Manual never changes.
    public static SubtitleMode OnMuteChanged(SubtitleMode current, bool nowMuted)
    {
        return (current, nowMuted) switch
        {
            (SubtitleMode.Off, true) => SubtitleMode.AutoMute,
            (SubtitleMode.AutoMute, false) => SubtitleMode.Off,
            _ => current
        };
    }

    /// A manual pick always yields Manual; a manual off always yields Off (even while muted).
    public static SubtitleMode OnManualPick(bool pickedOff)
    {
        return pickedOff ? SubtitleMode.Off : SubtitleMode.Manual;
    }
}
