namespace WinTube.Core.Player;

/// What the player should attach for a video, given the tracks and the persisted preference.
public static class SubtitleSelection
{
    /// Preference chain: manual track in the language → ASR track in the language →
    /// (preference "en" and no English track) translation of the default track → null.
    /// language match = languageCode equals preference OR starts with preference + "-".
    public static SubtitleChoice? Choose(IReadOnlyList<CaptionTrack> tracks, string? preferredLanguage)
    {
        if (preferredLanguage == null || tracks.Count == 0)
            return null;

        // First, look for manual (non-auto) track matching the language
        var manualMatch = tracks.FirstOrDefault(t =>
            !t.IsAutoGenerated &&
            LanguageMatches(t.Language, preferredLanguage));

        if (manualMatch != null)
            return new SubtitleChoice(
                manualMatch.VttUrl,
                manualMatch.Language,
                manualMatch.Name,
                false);

        // Second, look for ASR track matching the language
        var asrMatch = tracks.FirstOrDefault(t =>
            t.IsAutoGenerated &&
            LanguageMatches(t.Language, preferredLanguage));

        if (asrMatch != null)
            return new SubtitleChoice(
                asrMatch.VttUrl,
                asrMatch.Language,
                asrMatch.Name,
                false);

        // Third, if preference is "en" and no English track, return translation of first track
        if (preferredLanguage == "en")
        {
            var sourceTrack = tracks.FirstOrDefault(t => !t.IsAutoGenerated) ?? tracks[0];
            return new SubtitleChoice(
                sourceTrack.TranslatedVttUrl("en"),
                "en",
                "Translate to English",
                true);
        }

        return null;
    }

    private static bool LanguageMatches(string trackLanguage, string preferredLanguage)
    {
        return trackLanguage.Equals(preferredLanguage, StringComparison.Ordinal) ||
               trackLanguage.StartsWith(preferredLanguage + "-", StringComparison.Ordinal);
    }
}

/// A subtitle choice to attach. IsTranslation true means Url is the source track's TranslatedVttUrl("en");
/// false means Url is a track's VttUrl.
public sealed record SubtitleChoice(string Url, string Language, string Label, bool IsTranslation);

public enum SubtitleMode { Off, Manual, AutoMute }

/// Pure transition table for the mute automation. The caller owns current mode + muted flag.
public static class SubtitleMuteMachine
{
    /// Returns the new mode when mute state flips. Off+mute→AutoMute (callers attach the best
    /// track); AutoMute+unmute→Off; Manual never changes.
    public static SubtitleMode OnMuteChanged(SubtitleMode current, bool nowMuted)
    {
        return (current, nowMuted) switch
        {
            (SubtitleMode.Off, true) => SubtitleMode.AutoMute,
            (SubtitleMode.AutoMute, false) => SubtitleMode.Off,
            _ => current
        };
    }

    /// A manual pick always yields Manual; a manual off always yields Off (even while muted).
    public static SubtitleMode OnManualPick(bool pickedOff)
    {
        return pickedOff ? SubtitleMode.Off : SubtitleMode.Manual;
    }
}
